- name: restart prometheus
  service: name=prometheus state=restarted

- name: reload prometheus
  service: name=prometheus state=reloaded

- name: stop prometheus
  service: name=prometheus state=stopped
  
- name: restart node_exporter
  service: name=node_exporter state=stopped

- name: reload node_exporter
  service: name=node_exporter state=reloaded

- name: stop node_exporter
  service: name=node_exporter state=stopped

- name: start grafana-server
  service: name=grafana-server state=started


