---
- name: adding Oracle's PPA, then updating package repository
  apt_repository:
    repo: ppa:webupd8team/java

- name: update package index
  apt:
    update_cache: yes
- name: auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  sudo: yes
- name: install oracle-java
  apt:
    name: "{{ java_version }}"
- name: getting java_home path
  shell: dirname $(dirname $(readlink -f $(which java)))
  register: command_output

- lineinfile:
    path: /etc/environment
    line: JAVA_HOME="{{ command_output.stdout }}"

- name: reload source file
  shell: source /etc/environment
  args:
    executable: /bin/bash

